import { fakeRobot } from './fake-robot.js';
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser=await chromium.launch({...(process.env.CI?{}:{channel:'chrome'}),headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.addInitScript(fakeRobot);
 await page.goto(process.env.APP_URL||'http://localhost:8080');
 assert.equal(await page.locator('#arm').count(),0,'movement must not require a readiness checkbox');
 assert.equal(await page.locator('#neutralPose').count(),0,'measured robot neutral must not be replaceable from the main controls');
 assert.equal(await page.locator('#speechText,#voiceSelect,#audioFile,#audioPlayer').count(),0,'computer speech and audio controls must not be present');
 assert.equal(await page.locator('#jointControls .joint-card').count(),8);
 assert.equal(await page.locator('#mirrorStart,#mirrorStop,#humanNeutral').count(),0,'camera mode has no extra start or apply buttons');
 await page.locator('#connect').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('connected:'));
 await page.locator('[data-view=move]').click();await page.locator('#syncPose').click();await page.waitForFunction(()=>document.querySelector('#poseState').textContent.startsWith('Current pose'));
 await page.locator('[data-view=play]').click();await page.getByRole('button',{name:'Forward',exact:true}).click();
 await page.waitForFunction(()=>window.robotWrites.some(p=>p[0]===25&&p[1]===13));
 await page.waitForFunction(()=>window.robotWrites.some(p=>p[0]===25&&p[1]===8));
 assert.equal(await page.locator('#globalStop').isEnabled(),true);
 await page.locator('[data-view=move]').click();await page.locator('#syncPose').click();await page.waitForFunction(()=>document.querySelector('#poseState').textContent.startsWith('Current pose'));
 await page.locator('[data-view=workshop]').click();await page.getByText('Calibration · mapping, limits and direction',{exact:true}).click();
 await page.getByRole('checkbox',{name:'Right elbow enabled',exact:true}).check();
 await page.locator('[data-view=move]').click();const slider=page.getByRole('slider',{name:'Right elbow',exact:true});
 await slider.evaluate(el=>{el.value='136';el.dispatchEvent(new Event('input',{bubbles:true}));});
 await page.waitForFunction(()=>window.robotWrites.some(p=>p[0]===8&&p[1]===136));
 const poses=await page.evaluate(()=>window.robotWrites.filter(p=>p[0]===8));assert(poses.every(p=>p.slice(2,9).every(v=>v===128)));
 await page.locator('[data-view=create]').click();await page.locator('#poseName').fill('Test pose');await page.locator('#savePose').click();assert.equal(await page.locator('#savedPoses .saved-item').count(),1);
 await page.locator('[data-view=workshop]').click();await page.getByText('Robot sounds & clock · advanced',{exact:true}).click();await page.locator('#refreshBank').click();await page.waitForFunction(()=>document.querySelector('#presetSelect').options.length===20);
 await page.waitForFunction(()=>document.querySelector('#presetSelect').options[0]?.textContent.includes('INTRODUCE'));
 await page.locator('[data-view=play]').click();await page.locator('#quickJoke').click();
 await page.waitForFunction(()=>window.robotWrites.some(p=>p[0]===25&&p[1]===3&&p[2]===0));
 await page.locator('#quickTime').click();
 await page.waitForFunction(()=>window.robotWrites.some(p=>p[0]===27)&&window.robotWrites.some(p=>p[0]===25&&p[1]===18));
 await page.locator('[data-view=workshop]').click();await page.locator('#runTest').click();await page.waitForFunction(()=>document.querySelector('#testEvidence').textContent.includes('Record'));
 await page.getByRole('button',{name:'Working ✓',exact:true}).click();assert.match(await page.locator('#testTitle').textContent(),/Eyes/);
 await page.locator('[data-view=workshop]').click();await page.locator('#runTest').click();await page.waitForFunction(()=>window.robotWrites.some(p=>p[0]===17));
 await page.getByRole('button',{name:'Working ✓',exact:true}).click();
 await page.locator('#abortTest').click();
 await page.getByText('Experimental volume value',{exact:true}).click();await page.locator('#volumeCustom').fill('98');await page.locator('#volumeCustom').fill('99');await page.locator('#volumeCustom').press('Tab');await page.waitForFunction(()=>window.robotWrites.some(p=>p[0]===25&&p[1]===9&&p[2]===99));
 await page.locator('[data-view=play]').click();await page.locator('#volumeMedium').click();await page.waitForFunction(()=>window.robotWrites.some(p=>p[0]===25&&p[1]===9&&p[2]===2));
 await page.locator('[data-view=workshop]').click();await page.locator('#syncClock').click();await page.waitForFunction(()=>window.robotWrites.some(p=>p[0]===27));
 await page.locator('[data-view=copy]').click();await page.locator('#cameraStart').click();
 await page.waitForFunction(()=>document.querySelector('#cameraState').textContent.includes('Step into view')||document.querySelector('#cameraState').textContent.includes('Body tracked')||document.querySelector('#notice').textContent.includes('Error'),{},{timeout:45000});
 const cameraState=await page.locator('#cameraState').textContent();assert.match(cameraState,/Step into view|Body tracked/);
 assert.equal(await page.locator('#copyDrive').isEnabled(),true,'camera starts robot control without another button');
 assert.match(await page.locator('#mirrorState').textContent(),/controlling the robot|Waiting for camera — robot stopped/);
 await page.locator('#content').focus();const cameraPoseWrites=await page.evaluate(()=>window.robotWrites.filter(p=>p[0]===8).length);
 await page.keyboard.down('q');await page.waitForTimeout(350);await page.keyboard.up('q');
 assert(await page.evaluate(count=>window.robotWrites.filter(p=>p[0]===8).length>count,cameraPoseWrites),'joint key moves during camera mode');
 const cameraDriveWrites=await page.evaluate(()=>window.robotWrites.filter(p=>p[0]===25&&p[1]===13).length);
 const cameraStopWrites=await page.evaluate(()=>window.robotWrites.filter(p=>p[0]===25&&p[1]===8).length);
 await page.keyboard.down('ArrowUp');await page.waitForTimeout(300);await page.keyboard.up('ArrowUp');
 assert(await page.evaluate(count=>window.robotWrites.filter(p=>p[0]===25&&p[1]===13).length>count,cameraDriveWrites),'drive key moves during camera mode');
 await page.waitForFunction(count=>window.robotWrites.filter(p=>p[0]===25&&p[1]===8).length>count,cameraStopWrites);
 const copyForward=page.locator('#copyDrive [data-drive=forward]');assert.equal(await copyForward.isEnabled(),true);
 const cameraButtonDrives=await page.evaluate(()=>window.robotWrites.filter(p=>p[0]===25&&p[1]===13).length);
 await copyForward.hover();await page.mouse.down();await page.waitForTimeout(300);await page.mouse.up();
 await page.waitForFunction(count=>window.robotWrites.filter(p=>p[0]===25&&p[1]===13).length>count,cameraButtonDrives);
 assert.equal(await page.locator('#cameraStop').isEnabled(),true,'direction button leaves camera on');
 assert.equal(await page.locator('#cameraStop').isEnabled(),true,'joint keyboard override keeps camera running');
 await page.locator('#cameraStop').click();assert.equal(await page.locator('video').evaluate(v=>v.srcObject),null);
 await page.route('**/tracker-worker.js',route=>route.fulfill({contentType:'text/javascript',body:'self.onmessage=()=>{};'}));
 await page.locator('#cameraStart').click();assert.equal(await page.locator('#cameraStop').isEnabled(),true);
 assert.match(await page.locator('#cameraState').textContent(),/Getting the camera ready/);
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
 assert.equal(await page.locator('#cameraStop').isEnabled(),true,'camera permission focus change does not cancel setup');
 await page.locator('#cameraStop').click();await page.waitForFunction(()=>!document.querySelector('#cameraStart').disabled);
 assert.equal(await page.locator('video').evaluate(v=>v.srcObject),null);await page.unroute('**/tracker-worker.js');
 await mkdir('.local',{recursive:true});await page.screenshot({path:'.local/studio-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.local/studio-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 await page.locator('#globalStop').click();assert.equal(await page.locator('#motion').isEnabled(),true,'stopping does not introduce another readiness step');
 await page.locator('#disconnect').click();
 console.log('Browser checks passed: simulated BLE, joint preservation, saved pose, preset bank, guided tests, real local MediaPipe inference, camera cleanup, mobile layout.');
}finally{await browser.close();}
